### ISSUE TITLE
How to use this package with Puppeteer?

### ISSUE THREAD

**Issue by Napageneral** [fczbkk/css-selector-generator#457]
I have the following code snippet where I try to use this package to generate a unique css selector for an element obtained using a Puppeteer browser:

```
const oddsButtons = await marketsContainer.$$('li');
const generatorCode = fs.readFileSync(require.resolve('css-selector-generator'), 'utf-8');

await bot.page.evaluate((generatorCode) => {
    const script = document.createElement('script');
    script.textContent = generatorCode;
    document.head.appendChild(script);
}, generatorCode);

for (const oddButton of oddsButtons) {
    let generatorSelector = undefined;
    try {
        generatorSelector = await oddButton.evaluate((el) => {
            //@ts-ignore
            const generator = new window.CssSelectorGenerator();
            return generator.generate(el);
        });
    } catch (e) {
        console.log(e);
    }
    ...
}
```

However I end up getting the following exception:
```
Error: Evaluation failed: TypeError: window.CssSelectorGenerator is not a constructor
    at pptr://__puppeteer_evaluation_script__:3:43
    at ExecutionContext._ExecutionContext_evaluate (/Users/tylerbrandt/Packages/betGPT/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:252:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/Users/tylerbrandt/Packages/betGPT/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:140:16)
    at async CDPJSHandle.evaluate (/Users/tylerbrandt/Packages/betGPT/server/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:59:16)
```

This is likely not an issue with the package itself and more my inability to use it, however I'd really appreciate help getting this working if possible!

**Comment by fczbkk** [comment]
Hey @Napageneral, you can use something like this:

```javascript
import fs from 'node:fs/promises';
import puppeteer from 'puppeteer';

// load content of the library into a string
const CssSelectorGeneratorLibrary = await fs.readFile('./node_modules/css-selector-generator/build/index.js', 'utf-8');

// helper function that will later inject the library into the page
function injectJsToPage (page, js) {
  return page.evaluate((js) => {
    const scriptElement = document.createElement('script')
    scriptElement.textContent = js
    document.body.appendChild(scriptElement)
  }, js)
}

// create a Page object in Puppeteer
const browser = await puppeteer.launch({ headless: 'new' });
const page = await browser.newPage();

// you can either create the HTML for Page like this, or you can use
// `page.goto('https://my.website.com')` to load existing webpage
await page.setContent(`
    <html>
      <body>
        <p id="myElement"></p>
      </body>
    </html>
  `);

// inject library code into the page
await injectJsToPage(page, CssSelectorGeneratorLibrary)

// evaluate the script inside the page and send the resulting selector outside
const selector = await page.evaluate(() => {
  const element = document.querySelector('p');
  return CssSelectorGenerator.getCssSelector(element)
});

// do with the result whatever you want
console.log(selector); // <-- '#myElement'

// don't forget to clean up after yourself
await browser.close();

```
